### ISSUE TITLE
Do stress test on Azure Geoweaver

### ISSUE THREAD

**Issue by ZihengSun** [ESIPFed/Geoweaver#136]
http://20.75.224.129:8070/Geoweaver/web/geoweaver

This should be done before the sponsorship expires before April.

**Comment by uhhmed** [comment]
Two performance (Stress Tests) were performed on Geoweaver on azure host: http://20.75.224.129:8070

The 1st test (report attached below) focused on stressing the main page of Geoweaver (/Geoweaver/web/geoweaver) and was able to withstand:
- Azure node CPU increased to 38% and MEMORY to 60% indicating an active load.
- A total of 200 simultaneous threads (users).
- The load ramped up to 200 users within 8-9 minutes.
- The average response for each thread (users) was 608 ms.
- The fastest instance of a response for one of the threads was 74 ms, and the slowest was 10,635 ms.
- Total test duration was 10 minutes of constant requests from each thread (users).
- A total of 111,030 were made to the main geoweaver endpoint.
- No request failures (0 failures).
- For a total period of 10 seconds, some requests took as much as 10 seconds to respond (a very rare occurrence).
- 182.1 RPS (request per second) were made by the treads (aggregated).

The 2nd test using the same endpoint above but with a slightly increased user load. 
- Azure node CPU increased to 84% and MEMORY to 64% indicating an active load.
- A total of 250 simultaneous threads (users).
- The load ramped up to 250 users within 4 minutes.
- The average response for each thread (users) was 214 ms.
- The fastest instance of a response for one of the threads was 74 ms, and the slowest was 1339 ms.
- Total test duration was 5 minutes of constant requests from each thread (users).
- A total of 187,140 were made to the main geoweaver endpoint.
- No request failures (0 failures).
- Average response size (data returned) of 26,348 bytes.
- 611.9 RPS (request per second) were made by the treads (aggregated).

Below are the two reports for each stress mentioned summarized above:

[1st Test Report.pdf](https://github.com/ESIPFed/Geoweaver/files/6729605/1st.Test.Report.pdf)
[2nd Test Report.pdf](https://github.com/ESIPFed/Geoweaver/files/6729606/2nd.Test.Report.pdf)

**Comment by ZihengSun** [comment]
Thanks! This is done.
