### ISSUE TITLE
Need a stop button in the Weaver tab

### ISSUE THREAD

**Issue by didarul-csiss** [ESIPFed/Geoweaver#267]
Need a stop button in Geoweaver workflow to halt the processing if something goes wrong.

**Comment by ZihengSun** [comment]
Thanks! Can you see the stopping button in the history panel of workflow? You can access it by clicking the information icon button on the left toolbar.

**Comment by ZihengSun** [comment]
This should be changed to "Need a stop button in the Weaver tab".

**Comment by ZihengSun** [comment]
The stop button in the history table is actually not working.

**Comment by ZihengSun** [comment]
This is fixed
