### ISSUE TITLE
Can't add new python environment path from third party host while running workflow in Geoweaver.

### ISSUE THREAD

**Issue by didarul-csiss** [ESIPFed/Geoweaver#273]
I'm trying to run python script using workflow in Geoweaver. I connected with third party host to run the script. However, there is no option to add python environment path from third host in Geoweaver. But, I can add python environment path in the process by usng "New" option in the dropdown menue and can run the code. 

![Screenshot (1)](https://user-images.githubusercontent.com/88753494/152701255-c0c68ec5-7771-4a45-884f-77f2894fb133.png)

![Screenshot (3)](https://user-images.githubusercontent.com/88753494/152701259-b62de598-d5aa-4ef3-944c-6d3b6ebbc689.png)

**Comment by didarul-csiss** [comment]
Even if I create conda environment and install packages, I can add it in the process . But how can I add the path in the workflow if there is no option to add?

**Comment by ZihengSun** [comment]
@uhhmed can you take a look at this? I am kind sure that you will meet the same problem once your Hopper account is set. The idea is to create a personal condo environment under everyone's home directory. You will have full control over the env and install all the packages you need. Remember to save and share the requirements.txt.

**Comment by uhhmed** [comment]
Sure! Yeah I'm waiting on my account to be ready, but I think I have an idea how this should go. Just need to test it out once I have access.

**Comment by ZihengSun** [comment]
> I can create conda environment and install packages in third party host, and I can add it in the process . But how can I add the path in the workflow if there is no option to add?

@didarul-csiss after you create a new environment in process, the new env should show up in the workflow env list. Did it not?

**Comment by didarul-csiss** [comment]
No, it didn't show up.

**Comment by ZihengSun** [comment]
Well, that is a bug then. Please take a look at the `Environment` related code on the server side and see how to fix it.

**Comment by didarul-csiss** [comment]
This issue can be resolved by creating a python or conda environment in the remote host.

**Comment by ZihengSun** [comment]
@didarul-csiss can you describe the steps in details here? So other users to refer to it.

**Comment by didarul-csiss** [comment]
The above mentioned problem araise due to restriction of installing new packages in system directory. This issue can be resolve by creating conda or python virtual environment in home directory in remote host. 
Steps:
1. Create a folder in home directory.
2. Download/upload Anaconda and install it in the new folder. 
3. Select/add the installed python version (path) in Geoweaver from dropdown manue while executing the code in remote host.
4. Execute the code
