### ISSUE TITLE
End time is null for HOPPER

### ISSUE THREAD

**Issue by didarul-csiss** [ESIPFed/Geoweaver#291]
![image](https://user-images.githubusercontent.com/88753494/167873042-fe6365da-5fd3-4179-a274-5c4eeeb5e3f3.png)

**Comment by ZihengSun** [comment]
This issue is fixed in [commit](https://github.com/ZihengSun/Geoweaver/commit/7f427c3b7dc9f10285e91af92c2def95687ad46a)
