### ISSUE TITLE
h2 Error upon Geowever install

### ISSUE THREAD

**Issue by dliljest** [ESIPFed/Geoweaver#310]
when running java -jar geoweaver.jar I encounter an error which prevents it from installing. I tried both quick install and build from source. I've attached the error log, and pasted the head of it below.
[geoweaver_error.txt](https://github.com/ESIPFed/Geoweaver/files/9031438/geoweaver_error.txt)

(base) daneliljestrand@Danes-MacBook-Pro geoweaver % java -jar target/geoweaver.jar
INFO	2022-07-01 14:29:56,429	0	com.gw.GeoweaverApplication	[main]	Starting GeoweaverApplication v1.0.0-rc2 using Java 18.0.1.1 on Danes-MacBook-Pro.local with PID 5855 (/Users/daneliljestrand/Geoweaver/target/geoweaver.jar started by daneliljestrand in /Users/daneliljestrand/Geoweaver)
INFO	2022-07-01 14:29:56,430	1	com.gw.GeoweaverApplication	[main]	No active profile set, falling back to default profiles: default
INFO	2022-07-01 14:29:57,613	1184	org.springframework.data.repository.config.RepositoryConfigurationDelegate	[main]	Bootstrapping Spring Data JPA repositories in DEFAULT mode.
INFO	2022-07-01 14:29:57,752	1323	org.springframework.data.repository.config.RepositoryConfigurationDelegate	[main]	Finished Spring Data repository scanning in 128 ms. Found 7 JPA repository interfaces.
INFO	2022-07-01 14:29:58,873	2444	org.springframework.boot.web.embedded.tomcat.TomcatWebServer	[main]	Tomcat initialized with port(s): 8070 (http)
Jul 01, 2022 2:29:58 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Jul 01, 2022 2:29:58 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/9.0.41]
Jul 01, 2022 2:29:58 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring embedded WebApplicationContext
INFO	2022-07-01 14:29:58,956	2527	org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext	[main]	Root WebApplicationContext: initialization completed in 2434 ms
INFO	2022-07-01 14:29:59,022	2593	com.zaxxer.hikari.HikariDataSource	[main]	HikariPool-1 - Starting...
ERROR	2022-07-01 14:30:00,270	3841	com.zaxxer.hikari.pool.HikariPool	[main]	HikariPool-1 - Exception during pool initialization.
org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.NoClassDefFoundError: org/h2/util/NetworkConnectionInfo" [50000-210]

**Comment by ZihengSun** [comment]
https://github.com/h2database/h2database/commits/master/h2/src/main/org/h2/util/NetworkConnectionInfo.java 

The complained file is only available after 2019 June. It is probably that you have an older H2 library that is overwriting the one Geoweaver.jar has.

**Comment by ZihengSun** [comment]
I think we can close this. It seems to be a bug with the JDK environment setup. Should already be fixed.
