### ISSUE TITLE
History Chart is not sorted by date

### ISSUE THREAD

**Issue by ZihengSun** [ESIPFed/Geoweaver#352]
Actually not true. It is sorted but the latest date is in the front. The order should be ascending (old left, new right).
![image](https://user-images.githubusercontent.com/17322987/217144995-dc154033-5cb1-4c8b-a457-e6019d17e7ab.png)

**Comment by gokulprathin8** [comment]
Opened a PR @ https://github.com/ZihengSun/Geoweaver/pull/70

**Comment by ZihengSun** [comment]
Fixed by PR 70
