### ISSUE TITLE
fix the delete button of workflow

### ISSUE THREAD

**Issue by ZihengSun** [ESIPFed/Geoweaver#357]
After deleting a workflow, the area becomes blank, and if people click on the Weaver, the workflow processes are still there.

Idea:

Show people the result like "Workflow is deleted, and create another one or prompt some next steps for people to click". 

The leftover processes in Weaver view should be fixed. That is a bug.

**Comment by gokulprathin8** [comment]
@ZihengSun 
Please check the PR raised for the same, @ https://github.com/ZihengSun/Geoweaver/pull/73
