### ISSUE TITLE
Collect successful examples for demo and boosting user confidences

### ISSUE THREAD

**Issue by ZihengSun** [ESIPFed/Geoweaver#36]
One feedback from ESIP summer meeting 2019, one feedback is saying "Geoweaver need more successful example" to attract more community users.

**Comment by nachiketaraina** [comment]
is there any host server which can be accessed by the random user to try out  Geoweaver other than self initialized server

**Comment by ZihengSun** [comment]
> is there any host server which can be accessed by the random user to try out Geoweaver other than self initialized server

Good advice. I could try to set up a free-tire AWS instance as the demo instance.

**Comment by ZihengSun** [comment]
One example is here: https://github.com/earth-artificial-intelligence/kenya-crop-mask-geoweaver

**Comment by ZihengSun** [comment]
We now have a very good successful example: https://geobrain.csiss.gmu.edu/cmaq_site/index.html It was running operationally and Geoweaver gives a very solid performance and delivers AI prediction of Ozone every day.
