### ISSUE TITLE
Slider does not close

### ISSUE THREAD

**Issue by bhaba-ranjan** [ESIPFed/Geoweaver#369]
I am not sure if this is an expected behaviour. 

Here is how to reproduce it.

- Go to any workflow and click on a process.
- The editor slide will come form the left side.
- Select a host from the left side menu bar.
- The slider does not close. It stays open even in the host window at the back.

Please, close this issue, if this is an expected behaviour.

**Comment by gokulprathin8** [comment]
Hi @bhaba-ranjan ,

This is an issue. I have opened a PR @ https://github.com/ZihengSun/Geoweaver/pull/87
I will merge it shortly after testing.

Best,
G.

**Comment by gokulprathin8** [comment]
@bhaba-ranjan 
The PR is merged. 
Let me know if it works for you!

Best,
Gokul
