### ISSUE TITLE
Process getting deleted  from workflow

### ISSUE THREAD

**Issue by bhaba-ranjan** [ESIPFed/Geoweaver#372]
I download the latest jar file and imported my workflow.

After ***editing*** a ***dependent*** process and ***saving it*** (ctrl+s) the process is getting deleted from my workflow (sometimes) not all the time.

Do not have a exact way to reproduce it. But, I think it happens for the first time after using new jar file.

I faced this twice. 

Please,  take a look at the screen-shot attached.

Process and their corresponding links are deleted.

<img width="506" alt="Screenshot 2023-04-06 at 11 08 35 AM (2)" src="https://user-images.githubusercontent.com/112833588/230422637-4e26ab12-945f-49aa-902c-419e980db880.png">

Original workflow structure:

<img width="507" alt="Training_pipeline" src="https://user-images.githubusercontent.com/112833588/230423019-773ec3d7-77c5-40f8-b4a9-fc84cd93b727.png">

**Comment by gokulprathin8** [comment]
I'll take a look at this issue

**Comment by ZihengSun** [comment]
duplicated to #370
