### ISSUE TITLE
Geoweaver might not work in some Firefox version

### ISSUE THREAD

**Issue by ZihengSun** [ESIPFed/Geoweaver#379]
Need a broad test set for all browsers.

**Comment by gokulprathin8** [comment]
Version: 102.10.0esr (32-bit)

**Comment by ZihengSun** [comment]
We need a table of supported web browser minimum version.

**Comment by ZihengSun** [comment]
We have added cypress testing framework (thanks @meghanakr7 ). This should no longer be a concern.
