### ISSUE TITLE
This issue shows up again

### ISSUE THREAD

**Issue by ZihengSun** [ESIPFed/Geoweaver#490]
<img width="919" alt="image" src="https://github.com/ESIPFed/Geoweaver/assets/17322987/d9683409-6497-4482-b4d3-1fdff2a07502">

**Comment by ZihengSun** [comment]
The command run workflow just doesn't exit correctly for some reason and hangs forever.

**Comment by ZihengSun** [comment]
Not sure why but this log is too big

<img width="444" alt="image" src="https://github.com/ESIPFed/Geoweaver/assets/17322987/2ef7c78e-be3a-4592-befa-cadb8c1a6832">

**Comment by gokulprathin8** [comment]
the databse is 473gb? wow
there is definitely some duplication happening. I will check

**Comment by ZihengSun** [comment]
The doesn't exit problem is solved. That was a bug in the previous workflow execution logic, while the fast last step process will not be captured by the workflow status tracker.
