### ISSUE TITLE
The collapse button in the side panel is broken

### ISSUE THREAD

**Issue by ZihengSun** [ESIPFed/Geoweaver#491]
<img width="1336" alt="image" src="https://github.com/ESIPFed/Geoweaver/assets/17322987/30bf9426-35bc-48bf-b124-0aa3e12b7b85">

**Comment by gokulprathin8** [comment]
i pushed a fix for this @ https://github.com/ESIPFed/Geoweaver/pull/489
can you please re-verify if this is still happening 
@ZihengSun

**Comment by ZihengSun** [comment]
Yeah it is fixed.
