### ISSUE TITLE
issue in windows installation script for windows quick install

### ISSUE THREAD

**Issue by nachiketaraina** [ESIPFed/Geoweaver#53]
the windows installation script employs the use of Expand-Archive which contains extraction path and Destination Path both of which could be encapsulated within Quotation marks if either of the string contains space in between folder name, gives out   parameter binding exception error which could be solved by above said method.

C:/Users/test cap/ would give out error which can be solved by 
"C:/Users/test cap/" binding it in between quotation marks

**Comment by ZihengSun** [comment]
Thanks for pointing this out. Could you please be more specific about which line of the windows installation script? I tried on Windows 10 and it works for me.

**Comment by ZihengSun** [comment]
I see the script actually didn't run the cp, chmod and sleep commands because these are only existing in Linux. I will fix this now.

**Comment by nachiketaraina** [comment]
> Thanks for pointing this out. Could you please be more specific about which line of the windows installation script? I tried on Windows 10 and it works for me.

LINE NUMBER 37 AND 51 which are the powershell execution commands for Expand -Archive module execution in the install-windows.bat file gives out an error if the path strings contains space in between folder names. which  can be sorted out by using single quote quotation mark aptly

depending on the version of powershell upon these commands are executed switching the existing command with

powershell -Command " Expand-Archive -Path '%CD%\openjdk-12.0.2_windows-x64_bin.zip' -DestinationPath '%CD%\' "

extracts the zip file improves readability as well

**Comment by ZihengSun** [comment]
Great advice. A fix pull request has been merged.
